import { AdminProvider } from '@/context/AdminProvider'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Order (admin)',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     <AdminProvider><body className={inter.className}>{children}</body></AdminProvider>
    </html>
  )
}
